name: CI

# we can specify which github events will trigger a CI build
on: push

# now define a single job "build" (could have more)
jobs:

  build:

    # specify the OS to run on
    runs-on: ubuntu-latest

    # a job is a sequence of steps
    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up python 3.11
        uses: actions/setup-python@v6
        with:
          python-keyword: "3.11"

      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt .
      
      - name: Test with pytest
        run: |
          python3 -m pytest --cov=inflammation.models tests/test_models.pyt 

